export type AvailableIcons = 
  'ChevronDownIcon' |
  'ChevronUpDownIcon' |
  'ChevronsRightIcon' |
  'ArrowRightIcon' |
  'ArrowDownCircleIcon' |
  'CloseIcon' |
  'TrashIcon' |
  'PlusIcon' |
  'CheckedIcon' |
  'FileIcon' |
  'UploadIcon' |
  'ChatIcon' |
  'DashboardIcon' |
  'MoneyIcon' |
  'NotificationIcon' |
  'WorkflowIcon' |
  'SettingIcon' |
  'ArrowBackCircleIcon' |
  'FlowIcon' |
  'SaveIcon' |
  'FlowColorful' |
  'CheckedCircleIcon' |
  'EditIcon' |
  'TableIcon' |
  'ListIcon' |
  'DownloadAltIcon' |
  'ThunderIcon' |
  'MoreVerticalIcon' |
  'WindowsIcon' |
  'GitIcon' |
  'GitCompareIcon' |
  'WidgetIcon' |
  'FormIcon' |
  'DetalistIcon' |
  'EnvelopeIcon' |
  'SearchIcon' |
  'MenuIcon' |
  'MenuCollapsedIcon' |
  'HomeIcon' |
  'ProjectIcon' |
  'UsersIcon' |
  'UserIcon' |
  'ErrorCircleIcon' |
  'LockIcon' |
  'RefreshIcon' |
  'CloudIcon' |
  'InfoIcon' |
  'CalendarIcon' |
  'CompanyIcon' |
  'PencilIcon' |
  'MagicWandIcon' |
  'SquareCheckedIcon' |
  'PackageIcon' |
  'ReceiptIcon' |
  'MyDocsIcon' |
  'MyFinanceIcon' |
  'UserVoiceIcon' |
  'StopWatchIcon' |
  'MentionIcon' |
  'ArchiveIcon' |
  'EnvelopeOpenIcon' |
  'DropboxIcon' |
  'TrophyIcon' |
  'GameIcon' |
  'TriangleUpIcon' |
  'EquilizerIcon' |
  'TargetLockIcon' |
  'HourglassIcon' |
  'CompassIcon' |
  'TripIcon' |
  'ConnectionIcon' |
  'CarouselIcon' |
  'TimeIcon' |
  'CodeIcon' |
  'PlusCircleIcon' |
  'XCircleIcon' |
  'StatsIcon' |
  'HomeSaleIcon' |
  'CartIcon' |
  'PieChartIcon' |
  'CopyIcon' |
  'CloudRainIcon' |
  'PaperClipIcon' |
  'LikeIcon' |
  'UnlikeIcon' | 
  'MobileIcon' |
  'CollapseIcon' |
  'FilterIcon' |
  'WorldIcon' |
  'BullseyeIcon' |
  'BinocularsIcon' |
  'SortIcon' |
  'WhatsappIcon' |
  'PhoneOffIcon' |
  'WarningIcon' |
  'CalendarCheckIcon' |
  'FilterBarsIcon' |
  'PhoneCallIcon' |
  'GlobeIcon'