export const statesOfBrazil = [
  'Acre',
  'Alagoas',
  'Amapá',
  'Amazonas',
  'Bahia',
  'Ceará',
  'Distrito Federal',
  'Espírito Santo',
  'Goiás',
  'Maranhão',
  'Mato Grosso',
  'Mato Grosso do Sul',
  'Minas Gerais',
  'Pará',
  'Paraíba',
  'Paraná',
  'Pernambuco',
  'Piauí',
  'Rio de Janeiro',
  'Rio Grande do Norte',
  'Rio Grande do Sul',
  'Rondônia',
  'Roraima',
  'Santa Catarina',
  'São Paulo',
  'Sergipe',
  'Tocantins'
];

export const allCountries = [
  'Afeganistão',
  'África do Sul',
  'Albânia',
  'Alemanha',
  'Andorra',
  'Angola',
  'Antígua e Barbuda',
  'Arábia Saudita',
  'Argélia',
  'Argentina',
  'Armenia',
  'Austrália',
  'Áustria',
  'Azerbaijão',
  'Bahamas',
  'Bahrein',
  'Bangladesh',
  'Barbados',
  'Barein',
  'Bielorrússia',
  'Bélgica',
  'Belize',
  'Benin',
  'Bermudas',
  'Boșnia e Herzegovina',
  'Botswana',
  'Brasil',
  'Brunei',
  'Bulgária',
  'Burkina Faso',
  'Burundi',
  'Butão',
  'Cabo Verde',
  'Camarões',
  'Canadá',
  'Cazaquistão',
  'Camboja',
  'Catar',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Colômbia',
  'Comores',
  'Congo-Brazzaville',
  'Congo-Kinshasa',
  'Coreia do Norte',
  'Coreia do Sul',
  'Costa Rica',
  'Costa do Marfim',
  'Croácia',
  'Cuba',
  'Dinamarca',
  'Djibuti',
  'Dominica',
  'Egito',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Espanha',
  'Eswatini',
  'Estônia',
  'Eswatini',
  'Estados Unidos',
  'Eslováquia',
  'Eslovênia',
  'Etiópia',
  'Fiji',
  'Filipinas',
  'Finlândia',
  'França',
  'Gabão',
  'Gâmbia',
  'Gana',
  'Grécia',
  'Guatemala',
  'Guiné',
  'Guiné-Bissau',
  'Guiné Equatorial',
  'Haiti',
  'Holanda',
  'Honduras',
  'Hungria',
  'Iémen',
  'Ilhas Cook',
  'Ilhas Marshall',
  'Ilhas Salomão',
  'Ilhas Maurício',
  'Índia',
  'Indonésia',
  'Irã',
  'Iraque',
  'Irlanda',
  'Islândia',
  'Itália',
  'Jamaica',
  'Japão',
  'Jordânia',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letônia',
  'Libéria',
  'Líbano',
  'Líbia',
  'Liechtenstein',
  'Lituânia',
  'Luxemburgo',
  'Macedônia do Norte',
  'Madagáscar',
  'Malásia',
  'Malavi',
  'Maldivas',
  'Mali',
  'Malta',
  'Marrocos',
  'Mauritânia',
  'México',
  'Mianmar',
  'Moçambique',
  'Namíbia',
  'Nauru',
  'Nepal',
  'Nicarágua',
  'Níger',
  'Nigéria',
  'Noruega',
  'Nova Zelândia',
  'Omã',
  'Países Baixos',
  'Panamá',
  'Papua Nova Guiné',
  'Paquistão',
  'Paraguai',
  'Peru',
  'Polônia',
  'Portugal',
  'Quênia',
  'Quirguistão',
  'Reino Unido',
  'República Centro-Africana',
  'República Checa',
  'República Democrática do Congo',
  'República Dominicana',
  'Romênia',
  'Ruanda',
  'Rússia',
  'Saara Ocidental',
  'Samoa',
  'San Marino',
  'Santa Lúcia',
  'São Cristóvão e Nevis',
  'São Tomé e Príncipe',
  'Senegal',
  'Serra Leoa',
  'Sérvia',
  'Singapura',
  'Síria',
  'Somália',
  'Sri Lanka',
  'Suécia',
  'Suíça',
  'Suriname',
  'Tadjiquistão',
  'Tailândia',
  'Taiwan',
  'Tanzânia',
  'Trinidad e Tobago',
  'Tunísia',
  'Turcomenistão',
  'Turquia',
  'Tuvalu',
  'Uganda',
  'Ucrânia',
  'Emirados Árabes Unidos',
  'Uruguai',
  'Uzbequistão',
  'Vanuatu',
  'Vaticano',
  'Venezuela',
  'Vietnã',
  'Zâmbia',
  'Zimbábue'
];
